name: CI Pipeline

on:
  push:
    branches: [ "main", "test-ci" ]
  pull_request:
    branches: [ "main", "test-ci" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0  
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 15
    steps:
    - name: Configure system for MongoDB
      run: |
        sysctl -w vm.max_map_count=1677720
        sysctl -w vm.swappiness=1
        echo never > /sys/kernel/mm/transparent_hugepage/enabled

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      env:
        MONGO_URI: mongodb://localhost:27017
      run: pytest

    - name: Debug Mongo Logs
      if: failure()
      run: |
        docker inspect mongo
        docker logs $(docker ps -q --filter "name=mongo")
